version: '3'

networks:
  sdt:
    driver: bridge

volumes:
    sdt_be_data:

services:
  sdt_be:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: sdt:v1
    container_name: sdt
    ports:
      - 58082:8082
    volumes:
      - sdt_be_data:/app
    environment:
      - MYSQL_HOST=
      - MYSQL_PORT=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - REDIS_HOST=
      - REDIS_PORT=
      - REDIS_PASSWORD=
      - MINIO_ENDPOINT=
      - MINIO_ACCESS_KEY=
      - MINIO_SECRET_KEY=
      - MINIO_BUCKET=
      - OPENAI_URL=
      - OPENAI_API_KEY=
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 20s
      retries: 10
    networks:
      - sdt